### ISSUE TITLE
Connect to mysql 5.1 password problem

### ISSUE THREAD

**Issue by smpallen99** [xerions/mariaex#40] opened 2015-03-21 22:44 UTC
Thanks for the quick turnaround on  the last problem. Now I'm getting an error on password. I tried it both with providing password in the start_link and setting password in the env.

I get the following error when trying to connect to mysql 5.1.73

iex(1)> {:ok, p} = Mariaex.Connection.start_link(username: "root", database: "cebs_production")
** (exit) exited in: GenServer.call(#PID<0.113.0>, {:connect, [hostname: "localhost", password: "password", username: "root", database: "cebs_production"]}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Mariaex.Protocol.password/3
            lib/mariaex/protocol.ex:111: Mariaex.Protocol.password("", "password", "2Ou%RNpkF[v_Z&J'~jw:")
            lib/mariaex/protocol.ex:35: Mariaex.Protocol.dispatch/2
            lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
            lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
            (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
             lib/mariaex/connection.ex:63: Mariaex.Connection.start_link/1
iex(1)>
17:30:38.893 [error] GenServer #PID<0.113.0> terminating
Last message: {:tcp, #Port<0.5026>, <<52, 0, 0, 0, 10, 53, 46, 49, 46, 55, 51, 0, 14, 0, 0, 0, 50, 79, 117, 37, 82, 78, 112, 107, 0, 255, 247, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 70, 91, 118, 95, 90, ...>>}
State: %{backend_key: nil, opts: [hostname: "localhost", password: "password", username: "root", database: "cebs_production"], parameter_types: [], parameters: %{}, queue: {[{{:connect, [hostname: "localhost", password: "password", username: "root", database: "cebs_production"]}, {#PID<0.111.0>, #Reference<0.0.0.616>}}], []}, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.5026>}, sock_mod: Mariaex.Connection.Tcp, state: :handshake, state_data: nil, statement: nil, statement_id: nil, substate: nil, tail: "", types: :types_removed}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mariaex.Protocol.password/3
        lib/mariaex/protocol.ex:111: Mariaex.Protocol.password("", "password", "2Ou%RNpkF[v_Z&J'~jw:")
        lib/mariaex/protocol.ex:35: Mariaex.Protocol.dispatch/2
        lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
        lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

**Comment by liveforeverx** [comment] 2015-03-21 23:13
Thanks!

If mysql do not know auth plugins, it set mysql native password to empty string, fixed on master.

**Closed** 2015-03-22 00:05 UTC

**Comment by 2kodes** [comment] 2015-03-23 16:22
hi

I seem to be getting this error when connecting to MySQL 5.5.42. I currently have a phoenix app with ecto and mariaex as the adapter.It was working on mariaex 0.1.2 . however after i upgraded to version 0.1.3 today i get the following error



[error] GenServer #PID<0.2505.0> terminating
Last message: {:tcp, #Port<0.24245>, <<78, 0, 0, 0, 10, 53, 46, 53, 46, 52, 50, 45, 108, 111, 103, 0, 129, 1, 0, 0, 33, 79, 76, 110, 101, 49, 96, 112, 0, 255, 247, 33, 2, 0, 15, 128, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 53, ...>>}
State: %{backend_key: nil, opts: [port: 3306, timeout: 5000, otp_app: :nubs_congress, adapter: Ecto.Adapters.MySQL, database: "nubs_congress_2015_knust", username: "root", password: "askme", hostname: "localhost"], parameter_types: [], parameters: %{}, queue: {[{{:connect, [port: 3306, timeout: 5000, otp_app: :nubs_congress, adapter: Ecto.Adapters.MySQL, database: "nubs_congress_2015_knust", username: "root", password: "askme", hostname: "localhost"]}, {#PID<0.452.0>, #Reference<0.0.0.207763>}}], []}, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.24245>}, sock_mod: Mariaex.Connection.Tcp, state: :handshake, state_data: nil, statement: nil, statement_id: nil, substate: nil, tail: "", types: :types_removed}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mariaex.Protocol.password/3
        (mariaex) lib/mariaex/protocol.ex:109: Mariaex.Protocol.password(<<109, 121, 115, 113, 108, 95, 110, 97, 116, 105, 118, 101, 95, 112, 97, 115, 115, 119, 111, 114, 100, 0>>, "askme", "!OLne1`p5S%\\$8/#`>Q^")
        (mariaex) lib/mariaex/protocol.ex:35: Mariaex.Protocol.dispatch/2
        (mariaex) lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
        (mariaex) lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
[error] GenServer #PID<0.452.0> terminating
Last message: :query
State: %{conn: nil, link: nil, module: Ecto.Adapters.MySQL.Connection, params: [timeout: 5000, otp_app: :nubs_congress, adapter: Ecto.Adapters.MySQL, database: "nubs_congress_2015_knust", username: "root", password: "askme", hostname: "localhost"], sandbox: false, transactions: 0}
** (exit) an exception was raised:
    ** (ErlangError) erlang error: {{:function_clause, [{Mariaex.Protocol, :password, [<<109, 121, 115, 113, 108, 95, 110, 97, 116, 105, 118, 101, 95, 112, 97, 115, 115, 119, 111, 114, 100, 0>>, "askme", "!OLne1`p5S%\\$8/#`>Q^"], [file: 'lib/mariaex/protocol.ex', line: 109]}, {Mariaex.Protocol, :dispatch, 2, [file: 'lib/mariaex/protocol.ex', line: 35]}, {Mariaex.Connection, :process, 2, [file: 'lib/mariaex/connection.ex', line: 215]}, {Mariaex.Connection, :handle_info, 2, [file: 'lib/mariaex/connection.ex', line: 192]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 593]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 659]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}, {GenServer, :call, [#PID<0.2505.0>, {:connect, [port: 3306, timeout: 5000, otp_app: :nubs_congress, adapter: Ecto.Adapters.MySQL, database: "nubs_congress_2015_knust", username: "root", password: "askme", hostname: "localhost"]}, 5000]}}
        (elixir) lib/gen_server.ex:356: GenServer.call/3
        (mariaex) lib/mariaex/connection.ex:63: Mariaex.Connection.start_link/1
        (ecto) lib/ecto/adapters/sql/worker.ex:96: Ecto.Adapters.SQL.Worker.handle_call/3
        (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3


Trying with Mariaex.COnnection.start_link also brings up the following error, which seems similar. I'm guessing the issue is with the password function or option. 


** (exit) exited in: GenServer.call(#PID<0.2535.0>, {:connect, [hostname: "localhost", username: "root", database: "nubs_congress_2015_knust", password: "askme"]}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Mariaex.Protocol.password/3
            (mariaex) lib/mariaex/protocol.ex:109: Mariaex.Protocol.password(<<109, 121, 115, 113, 108, 95, 110, 97, 116, 105, 118, 101, 95, 112, 97, 115, 115, 119, 111, 114, 100, 0>>, "askme", "FwG:+iR<u[I9$DigFja*")
            (mariaex) lib/mariaex/protocol.ex:35: Mariaex.Protocol.dispatch/2
            (mariaex) lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
            (mariaex) lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
            (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
     (elixir) lib/gen_server.ex:356: GenServer.call/3
    (mariaex) lib/mariaex/connection.ex:63: Mariaex.Connection.start_link/1
iex(23)> [error] GenServer #PID<0.2535.0> terminating
Last message: {:tcp, #Port<0.25982>, <<78, 0, 0, 0, 10, 53, 46, 53, 46, 52, 50, 45, 108, 111, 103, 0, 134, 1, 0, 0, 70, 119, 71, 58, 43, 105, 82, 60, 0, 255, 247, 33, 2, 0, 15, 128, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 117, ...>>}
State: %{backend_key: nil, opts: [hostname: "localhost", username: "root", database: "nubs_congress_2015_knust", password: "askme"], parameter_types: [], parameters: %{}, queue: {[{{:connect, [hostname: "localhost", username: "root", database: "nubs_congress_2015_knust", password: "askme"]}, {#PID<0.453.0>, #Reference<0.0.1.108346>}}], []}, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.25982>}, sock_mod: Mariaex.Connection.Tcp, state: :handshake, state_data: nil, statement: nil, statement_id: nil, substate: nil, tail: "", types: :types_removed}
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mariaex.Protocol.password/3
        (mariaex) lib/mariaex/protocol.ex:109: Mariaex.Protocol.password(<<109, 121, 115, 113, 108, 95, 110, 97, 116, 105, 118, 101, 95, 112, 97, 115, 115, 119, 111, 114, 100, 0>>, "askme", "FwG:+iR<u[I9$DigFja*")
        (mariaex) lib/mariaex/protocol.ex:35: Mariaex.Protocol.dispatch/2
        (mariaex) lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
        (mariaex) lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

**Comment by 2kodes** [comment] 2015-03-23 16:23
ps: sorry for the long stacktrace

**Comment by liveforeverx** [comment] 2015-03-23 18:15
Thanks, it is related to #39. It is a [regression](https://github.com/xerions/mariaex/commit/823856881cd585fb180d0395ff7e665d42624134). We are fixing it and make regression tests, and release new version today. Sorry for inconvenience.

**Comment by 2kodes** [comment] 2015-03-23 18:22
No problem. Thanks for the quick reply...

**Comment by liveforeverx** [comment] 2015-03-23 21:49
@2kodes It released, should working now.

**Comment by 2kodes** [comment] 2015-03-24 11:45
hi,
Just to confirm its working now with the latest version 0.1.4. Thanks a lot. :+1:

**Comment by homanchou** [comment] 2019-02-13 23:29
Is this problem I'm having related at all?  https://stackoverflow.com/questions/54680958/mysql-connection-error-on-a-new-phoenix-1-4-project

**Comment by wojtekmach** [comment] 2019-02-13 23:56
@homanchou Since you're using MySQL 8.0, I suspect the problem is that released Mariaex versions do not support default auth plugin on that version, caching_sha2_password. You may try Mariaex master for that. Alternatively, you can change the default auth plugin in your database to `mysql_native_password`.

You can check what's the auth plugin by running this:

```sql
mysql> select user, plugin from mysql.user;
```

If that's not it, please add `show_sensitive_data_on_connection_error: true` to your Repo config and pass the exact error you're getting.

**Comment by revati** [comment] 2019-02-24 15:07
Hello, i have encountered the same issue, it seems.

- phoenix: `1.4.1`
- mariaex: `0.9.1`

Trying to connect to to mysql 8 (successfully connected with Sequel Pro)
Added `show_sensitive_data_on_connection_error: true` to Repo config.
But still get this error, while connecting to db:

```
$ mix ecto.create

17:03:34.672 [error] GenServer #PID<0.206.0> terminating
** (FunctionClauseError) no function clause matching in Mariaex.Protocol.password/3
    (mariaex) lib/mariaex/protocol.ex:1092: Mariaex.Protocol.password(<<99, 97, 99, 104, 105, 110, 103, 95, 115, 104, 97, 50, 95, 112, 97, 115, 115, 119, 111, 114, 100, 0>>, "secret", <<97, 2, 75, 96, 117, 67, 46, 3, 38, 83, 37, 13, 113, 124, 22, 93, 84, 127, 118, 120>>)
    (mariaex) lib/mariaex/protocol.ex:212: Mariaex.Protocol.handle_handshake/3
    (mariaex) lib/mariaex/protocol.ex:171: Mariaex.Protocol.handshake_recv/2
    (db_connection) lib/db_connection/connection.ex:66: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mariaex.Protocol
** (Mix) The database for Blog.Repo couldn't be created: %RuntimeError{message: "killed"}
```

Mysql have reverted to mysql 5.7 way of handling password encryption
```
mysql> select user, plugin from mysql.user;
+------------------+-----------------------+
| user             | plugin                |
+------------------+-----------------------+
| root             | mysql_native_password |
| mysql.infoschema | caching_sha2_password |
| mysql.session    | caching_sha2_password |
| mysql.sys        | caching_sha2_password |
+------------------+-----------------------+
4 rows in set (0.00 sec)
```

---

*Update*

Changing `mariaex` dependency to master with `{:mariaex, github: "xerions/mariaex", branch: "master", override: true}` fixes issue :)

**Comment by ckreiling** [comment] 2019-03-04 01:49
I'm seeing the exact same problem as @wojtekmach in an app I just spun up.

`elixir: 1.8`
`ecto_sql: "~> 3.0.5"`
`mariaex: "~> 0.9.2"`
