### ISSUE TITLE
Insert incorrectly failing 

### ISSUE THREAD

**Issue by smpallen99** [xerions/mariaex#41] opened 2015-03-22 00:39 UTC
The following insert is failing. However, if I remove  the first field, it passes. 

```elixir```
iex(7)> Conn.query p, "INSERT INTO messages (`address_position`, `created_at`, `from`, `message_type`, `messageable_id`, `messageable_type`, `queue_position`, `receiver_id`, `receiver_type`, `retry_attempt`, `sender_id`, `sender_type`, `status`, `to`, `topic`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [nil, {{2015, 3, 21}, {23, 3, 41, 0}}, nil, "Call", 94, "MultipartyNotification", nil, 1514, "Contact", nil, 1514, "Contact", "initial", "UCX/300@300", "Lab", {{2015, 3, 21}, {23, 3, 41, 0}}]
[warn] connection.query message: {:query, "INSERT INTO messages (`address_position`, `created_at`, `from`, `message_type`, `messageable_id`, `messageable_type`, `queue_position`, `receiver_id`, `receiver_type`, `retry_attempt`, `sender_id`, `sender_type`, `status`, `to`, `topic`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [nil, {{2015, 3, 21}, {23, 3, 41, 0}}, nil, "Call", 94, "MultipartyNotification", nil, 1514, "Contact", nil, 1514, "Contact", "initial", "UCX/300@300", "Lab", {{2015, 3, 21}, {23, 3, 41, 0}}], []}
{:error,
 %Mariaex.Error{mariadb: %{code: 1048,
    message: "Column 'created_at' cannot be null"}, message: nil}}
iex(8)> Conn.query p, "INSERT INTO messages (`created_at`, `from`, `message_type`, `messageable_id`, `messageable_type`, `queue_position`, `receiver_id`, `receiver_type`, `retry_attempt`, `sender_id`, `sender_type`, `status`, `to`, `topic`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [{{2015, 3, 21}, {23, 3, 41, 0}}, nil, "Call", 94, "MultipartyNotification", nil, 1514, "Contact", nil, 1514, "Contact", "initial", "UCX/300@300", "Lab", {{2015, 3, 21}, {23, 3, 41, 0}}]
[warn] connection.query message: {:query, "INSERT INTO messages (`created_at`, `from`, `message_type`, `messageable_id`, `messageable_type`, `queue_position`, `receiver_id`, `receiver_type`, `retry_attempt`, `sender_id`, `sender_type`, `status`, `to`, `topic`, `updated_at`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [{{2015, 3, 21}, {23, 3, 41, 0}}, nil, "Call", 94, "MultipartyNotification", nil, 1514, "Contact", nil, 1514, "Contact", "initial", "UCX/300@300", "Lab", {{2015, 3, 21}, {23, 3, 41, 0}}], []}
{:ok,
 %Mariaex.Result{columns: [], command: :insert, last_insert_id: 13954,
  num_rows: 1, rows: nil}}
iex(9)>
```
Here is the schema for the table:
```
mysql> describe messages;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| id               | int(11)      | NO   | PRI | NULL    | auto_increment |
| topic            | varchar(255) | YES  |     | NULL    |                |
| status           | varchar(255) | YES  |     | initial |                |
| to               | varchar(255) | YES  |     | NULL    |                |
| from             | varchar(255) | YES  |     | NULL    |                |
| message_type     | varchar(255) | YES  |     | NULL    |                |
| messageable_type | varchar(255) | YES  |     | NULL    |                |
| messageable_id   | int(11)      | YES  |     | NULL    |                |
| sender_type      | varchar(255) | YES  |     | NULL    |                |
| sender_id        | int(11)      | YES  |     | NULL    |                |
| receiver_type    | varchar(255) | YES  |     | NULL    |                |
| receiver_id      | int(11)      | YES  |     | NULL    |                |
| created_at       | datetime     | NO   |     | NULL    |                |
| updated_at       | datetime     | NO   |     | NULL    |                |
| address_position | int(11)      | YES  |     | 0       |                |
| retry_attempt    | int(11)      | YES  |     | 0       |                |
| queue_position   | int(11)      | YES  |     | NULL    |                |
+------------------+--------------+------+-----+---------+----------------+
17 rows in set (0.00 sec)
```

**Comment by liveforeverx** [comment] 2015-03-22 01:42
The error is coming directly from database, seems not to be an error on client.

After checking different [stackoverflow](http://stackoverflow.com/questions/6248983/mysql-column-cannot-be-null) threads for this mysql errors, it possibly, that your have triggers in database affecting this fields (address_position).

```
show triggers like 'messages';
show triggers;
```

**Comment by smpallen99** [comment] 2015-03-22 02:01
just checked. no triggers. 

I'll get a wireshark trace in the morning and see if that gives any clues.

**Comment by liveforeverx** [comment] 2015-03-22 11:04
Yesterday, I can't reproduce it, because my MySQL doesn't allows to create [reserved words](http://dev.mysql.com/doc/refman/5.5/en/reserved-words.html), today I have reproduced it with fields from1, to1

```
MySQL [abc]> describe messages;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| id               | int(11)      | NO   | PRI | NULL    | auto_increment |
| topic            | varchar(255) | YES  |     | NULL    |                |
| status           | varchar(255) | YES  |     | NULL    |                |
| to1              | varchar(255) | YES  |     | NULL    |                |
| from1            | varchar(255) | YES  |     | NULL    |                |
| message_type     | varchar(255) | YES  |     | NULL    |                |
| messageable_type | varchar(255) | YES  |     | NULL    |                |
| messageable_id   | int(11)      | YES  |     | NULL    |                |
| sender_type      | varchar(255) | YES  |     | NULL    |                |
| sender_id        | int(11)      | YES  |     | NULL    |                |
| receiver_type    | varchar(255) | YES  |     | NULL    |                |
| receiver_id      | int(11)      | YES  |     | NULL    |                |
| created_at       | datetime     | NO   |     | NULL    |                |
| updated_at       | datetime     | NO   |     | NULL    |                |
| address_position | int(11)      | YES  |     | 0       |                |
| retry_attempt    | int(11)      | YES  |     | 0       |                |
| queue_position   | int(11)      | YES  |     | NULL    |                |
+------------------+--------------+------+-----+---------+----------------+
17 rows in set (0.01 sec)
```

starting to search.

**Comment by liveforeverx** [comment] 2015-03-22 12:17
Fixed on master

**Closed** 2015-03-22 14:25 UTC
Labels: bug
