### ISSUE TITLE
Anyone else had issue with mysql 5.7.9?

### ISSUE THREAD

**Issue by leiyangyou** [xerions/mariaex#83] opened 2015-12-01 12:33 UTC
DDLs would still execute, but all select statements would timeout

**Comment by ericmj** [comment] 2015-12-01 16:17
Have you confirmed that it only happens with mysql 5.7.9? Have you tried other versions and they work?

**Comment by liveforeverx** [comment] 2015-12-01 23:36
I've checked last 5.6.X version, it works, on 5.7.X there all close to all mariaex tests failing(going to check MySQL changelog).

**Comment by liveforeverx** [comment] 2015-12-02 00:11
The reason, which I see, is, that MySQL 5.7.9 doesn't send EOF on stmt_prepare_ok after the last column definitions. As the stmt_prepare_ok sends the number of parameters...

Probably it can be a bug or optimisation (to not send last EOF).

I'll try to find it out.

**Comment by liveforeverx** [comment] 2015-12-08 21:20
So, information, the protocol is changed somewhere in 5.7.5, I have done working version last week, where only 4 tests are failing now.

I need to do 2 steps: 
1) Experiment little bit and find a best way to support protocol before 5.7.5 changes.
2) 4 failing tests, something changed in some types handling with new version.

**Comment by liveforeverx** [comment] 2015-12-08 23:54
Ok, I've implemented the version switch and documented problem, and will release new version soon.

**Comment by liveforeverx** [comment] 2015-12-08 23:58
Version 0.6.1 released with support for MySQL 5.7.

**Closed by liveforeverx** 2015-12-08 23:58 UTC

**Comment by liveforeverx** [comment] 2015-12-09 00:03
MySQL have done the backwards incompatible changes in protocol, which I haven't found yet, how to
integrate without a explicit check on MySQL 5.7, because there is no change in protocol versions.

Documented here: https://github.com/xerions/mariaex/blob/master/lib/mariaex/protocol.ex#L105-L112
