### ISSUE TITLE
Cannot connect to mysql 5.1

### ISSUE THREAD

**Issue by smpallen99** [xerions/mariaex#39] opened 2015-03-21 20:05 UTC
I get the following error when trying to connect to mysql 5.1.73

iex(2)> {:ok, p} = Mariaex.Connection.start_link(hostname: "127.0.0.1", username: "root", password: "********", database: "cebs_production")
** (exit) exited in: GenServer.call(#PID<0.118.0>, {:connect, [hostname: "127.0.0.1", username: "root", password: "********", database: "cebs_production"]}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: [""]
            lib/mariaex/messages.ex:85: Mariaex.Messages.decode_handshake/1
            lib/mariaex/messages.ex:255: Mariaex.Messages.decode/2
            lib/mariaex/connection.ex:210: Mariaex.Connection.process/2
            lib/mariaex/connection.ex:191: Mariaex.Connection.handle_info/2
            (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

14:45:19.075 [error] GenServer #PID<0.118.0> terminating
Last message: {:tcp, #Port<0.5128>, <<52, 0, 0, 0, 10, 53, 46, 49, 46, 55, 51, 0, 250, 6, 0, 0, 112, 87, 66, 37, 47, 93, 105, 119, 0, 255, 247, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 86, 37, 85, 93, ...>>}
State: %{backend_key: nil, opts: [hostname: "127.0.0.1", username: "root", password: "********", database: "cebs_production"], parameter_types: [], parameters: %{}, queue: {[{{:connect, [hostname: "127.0.0.1", username: "root", password: "********", database: "cebs_production"]}, {#PID<0.105.0>, #Reference<0.0.0.575>}}], []}, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.5128>}, sock_mod: Mariaex.Connection.Tcp, state: :handshake, state_data: nil, statement: nil, statement_id: nil, substate: nil, tail: "", types: :types_removed}
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: [""]
        lib/mariaex/messages.ex:85: Mariaex.Messages.decode_handshake/1
        lib/mariaex/messages.ex:255: Mariaex.Messages.decode/2
        lib/mariaex/connection.ex:210: Mariaex.Connection.process/2
        lib/mariaex/connection.ex:191: Mariaex.Connection.handle_info/2
        (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:356: GenServer.call/3
             lib/mariaex/connection.ex:63: Mariaex.Connection.start_link/1
iex(2)>

**Comment by liveforeverx** [comment] 2015-03-21 20:23
Hi! Thanks for reporting! Can you please record with tcpdump the first packet, that mysql sends or better with a debugger tool the call (for example using [exrun](https://github.com/liveforeverx/exrun)) the packet, that it tries to decode.

With exrun it would be:

```elixir
import Tracer; trace Mariaex.Messages.decode_handshake
{:ok, p} = Mariaex.Connection.start_link(username: "ecto", database: "ecto_test")
#PID<0.168.0> call Mariaex.Messages.decode_handshake(<<10, 53, 46, 53, 46, 53, 45, 49, 48, 46, 48, 46, 49, 51, 45, 77, 97, 114, 105, 97, 68, 66, 0, 229, 4, 0, 0, 106, 44, 57, 121, 121, 113, 77, 107, 0, 255, 247, 33, 2, 0, 63, 160, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82, 58, 106, 42, 49, 84, 54, 80, 112, 100, 38, 45, 0, 109, 121, 115, 113, 108, 95, 110, 97, 116, 105, 118, 101, 95, 112, 97, 115, 115, 119, 111, 114, 100, 0>>)
```

Thanks beforehand.

**Comment by liveforeverx** [comment] 2015-03-21 20:49
I can reproduce it on my notebook with mysql 5.1.73, will check it.

**Comment by liveforeverx** [comment] 2015-03-21 21:11
Fixed on master, I'll release version 0.1.2 tomorrow.

**Comment by umatomba** [comment] 2015-03-23 16:45
after fix in https://github.com/xerions/mariaex/commit/823856881cd585fb180d0395ff7e665d42624134
the password/3 function don't make binary matching correclty:

17:24:52.236 [error] GenServer #PID<0.225.0> terminating
Last message: {:tcp, #Port<0.14049>, <<109, 0, 0, 0, 10, 53, 46, 53, 46, 53, 45, 49, 48, 46, 48, 46, 49, 54, 45, 77, 97, 114, 105, 97, 68, 66, 45, 49, 126, 112, 114, 101, 99, 105, 115, 101, 45, 119, 115, 114, 101, 112, 45, 108, 111, 103, 0, 133, ...>>}
State: %{backend_key: nil, opts: [timeout: 5000, otp_app: :exd_charging, adapter: Ecto.Adapters.MySQL, database: "tetete", username: "galera", password: "galera", hostname: "192.168.13.111", port: 3307], parameter_types: [], parameters: %{}, queue: {[{{:connect, [timeout: 5000, otp_app: :exd_charging, adapter: Ecto.Adapters.MySQL, database: "tetete", username: "galera", password: "galera", hostname: "192.168.13.111", port: 3307]}, {#PID<0.218.0>, #Reference<0.0.0.3447>}}], []}, rows: [], seqnum: 0, sock: {Mariaex.Connection.Tcp, #Port<0.14049>}, sock_mod: Mariaex.Connection.Tcp, state: :handshake, state_data: nil, statement: nil, statement_id: nil, substate: nil, tail: "", types: :types_removed}
** (FunctionClauseError) no function clause matching in Mariaex.Protocol.password/3
    lib/mariaex/protocol.ex:110: Mariaex.Protocol.password(<<109, 121, 115, 113, 108, 95, 110, 97, 116, 105, 118, 101, 95, 112, 97, 115, 115, 119, 111, 114, 100, 0>>, "galera", "::Sq`o-0Jb.^n.8oGUV0")
    lib/mariaex/protocol.ex:35: Mariaex.Protocol.dispatch/2
    lib/mariaex/connection.ex:215: Mariaex.Connection.process/2
    lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
    (stdlib) gen_server.erl:599: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
** (exit) exited in: GenServer.call(#PID<0.218.0>, :query, 5000)
    ** (EXIT) exited in: GenServer.call(#PID<0.225.0>, {:connect, [timeout: 5000, otp_app: :exd_charging, adapter: Ecto.Adapters.MySQL, database: "tetete", username: "galera", password: "galera", hostname: "192.168.13.111", port: 3307]}, 5000)

Possible solution https://github.com/umatomba/mariaex/commit/54e2ce986b25a75b5b8f48b02a170387b49cb2a8

**Comment by liveforeverx** [comment] 2015-03-23 17:00
Due to [bug](http://bugs.mysql.com/bug.php?id=59453), we should support both.

**Comment by liveforeverx** [comment] 2015-03-23 21:34
Closed on master

**Closed by liveforeverx** 2015-03-23 21:34 UTC
